# kubectl apply -f deployment.yml
apiVersion: app/v1
kind: Deployment
metadata:
  name: gemini-app
  namespace: cristopher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gemini-app
  template:
    metadata:
      labels: 
        app: gemini-app
    spec:
      containers:
      - name: gemini-container
        image: cristopherguzman/gemini-app:latest   # Reemplaza con la imagen de tu aplicación Gemini en DockerHub
        imagePullPolicy: IfNotPresent           # Evita bajar la imagen si ya existe
        envFrom:
            - secretRef:
                name: credentials               # Cargar todo el Secret como variables de entorno