# kubectl apply -f secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: cristopher
type: Opaque
data:
  # Credenciales de la base de datos y RapidAPI en Base64
  DATABASE_URL: bW9uZ29kYitzcnY6Ly9jcmlzdG9waGVyZ3V6bWFuOm9yVElXTDExME5tRkFvM1M1QGNsdXN0ZXIwLm84c2M5Lm1vbmdvZGIubmV0L2dlbWluaT9yZXRyeVdyaXRlcz10cnVlJndPZk1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=
  DATABASE_USERNAME: Y3Jpc3RvcGhlcmd1em1hbg==
  DATABASE_PASSWORD: b3JUSVdMMTBObUZBbzNTNQ==
  API_URL: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
  APIKEY: AIzaSyBPvEaC_Em6lJYhuudjBlBi1jaoE4hXJ0g

# echo -n "my-user" | base64
# echo -n "my-password" | base64
# echo "bXktdXNlcg==" | base64 --decode