# docker-compose up
# docker-compose down
version: "3.8"

services:
  age-detector-be:                             # Nombre del servicio
    image: gemini-spring-boot:latest # Nombre de la imagen a utilizar (se construirá con el Dockerfile)
    container_name: gemini-spring-boot-container # Nombre específico para el contenedor
    ports:
      - "8080:8080" # Mapea el puerto 8080 del host al 8080 del contenedor
    environment:
      SPRING_PROFILES_ACTIVE: docker # Activa el perfil 'docker' en Spring Boot
      SPRING_DATASOURCE_URL: "jdbc:postgresql://host.docker.internal:5432/gemini_db" # URL de la base de datos PostgreSQL (asumiendo que corre en el host o en otro contenedor accesible)
      SPRING_DATASOURCE_USERNAME: "cristopherguzman" # Reemplaza con tu usuario de base de datos
      SPRING_DATASOURCE_PASSWORD: "orTIWL10NmFAo3S5" # Reemplaza con tu contraseña de base de datos
    build: . # Indica a Docker Compose que construya la imagen a partir del Dockerfile en el directorio actual